# store in src/weigh/secrets.toml
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "wyojustin@gmail.com"
sender_password = "cilp oniq snhg aymj"
default_recipient = "wyoamy@gmail.com"
